## EDA

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("./../data/raw/train.csv")

In [3]:
df.head()

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate
0,4a16050093a99092,"No, you have to prove that I can't.",0,0,0,0,0,0
1,6bc2122dc27e275a,Re: My major edit summaries \n\nI have receive...,0,0,0,0,0,0
2,5570f7207bade92f,I depersonalized it. It's sad how you don't ob...,0,0,0,0,0,0
3,a17d6408ffb98139,Thats because I was blocked before I could dis...,0,0,0,0,0,0
4,11b1d25d77ffd834,"I apologise for this, I was just angry with ha...",0,0,0,0,0,0

In [4]:
df.describe()

,toxic,severe_toxic,obscene,threat,insult,identity_hate
count,111699.000000,111699.000000,111699.000000,111699.000000,111699.000000,111699.000000
mean,0.095534,0.010116,0.052695,0.003142,0.049544,0.008863
std,0.293952,0.100071,0.223425,0.055969,0.217002,0.093726
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [9]:
df['summarize'] = (df['toxic'] + df['severe_toxic'] + df['obscene'] + df['threat'] + df['insult'] + df['identity_hate'])

In [10]:
df.describe()

,toxic,severe_toxic,obscene,threat,insult,identity_hate,summarize
count,111699.000000,111699.000000,111699.000000,111699.000000,111699.000000,111699.000000,111699.000000
mean,0.095534,0.010116,0.052695,0.003142,0.049544,0.008863,0.219895
std,0.293952,0.100071,0.223425,0.055969,0.217002,0.093726,0.749348
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000

In [12]:
df[df['summarize'] > 0].describe()

,toxic,severe_toxic,obscene,threat,insult,identity_hate,summarize
count,11317.000000,11317.000000,11317.000000,11317.000000,11317.000000,11317.000000,11317.000000
mean,0.942918,0.099850,0.520103,0.031015,0.488999,0.087479,2.170363
std,0.232010,0.299813,0.499618,0.173367,0.499901,0.282548,1.144150
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000
50%,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,2.000000
75%,1.000000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,6.000000

Примерно 11-12% комментариев - токсичны. При этом в среднем присутствует минимум две метки

In [16]:
df[(df['summarize'] >= 1) & (df['toxic'] == 0)]

,id,comment_text,toxic,severe_toxic,obscene,threat,insult,identity_hate,summarize
94,252b47fe435c0607,"Oh, give me a break. If you'd been watching m...",0,0,1,0,0,0,1
185,15ff5bd9afba3bce,"All my answers were given, i am not banned on ...",0,0,1,0,1,0,2
212,c3589a6658f8f0f5,"Stay out of this, fat boy. We're not in Japan,...",0,0,0,0,1,1,2
1204,b47050d47d040513,John Edward \n\nHi \n\nThis topic is getting r...,0,0,1,0,0,0,1
1384,98230b6e403cf3c8,Silly guy. You should use email like the wikij...,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...
110404,f24a0fcc1f403334,yeah after few days some jews will say nasser ...,0,0,0,0,0,1,1
110880,84f7459a433a5ab9,"Blocking user: Willybigcheese \nHi, ummmmmm wt...",0,0,1,0,0,0,1
111245,636eaca482edf67e,the ridiculous vandalism on this page \n\npeop...,0,0,1,0,0,0,1
111297,ed9bf670451fa629,Jime1138 I never said the articled was retract...,0,0,1,0,0,0,1
111401,c4ad5422cf539066,"""\n\n Hi nerd \n\nWould you please explain why...",0,0,1,0,1,0,2

У нас присутствуют каждая категория по отдельности, т.е. метка toxic -- не панацея и не универсальная таблетка. Создадим колонку negative = summarize > 0 -- комментарии, в которых присутствует хоть что-то негативное. Остальные удалим в целях упрощения учебного проекта

In [25]:
df = df.drop(axis='columns', labels=['id', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate'])

In [36]:
df = df.copy()
df['negative'] = (df['summarize'] > 0).astype(int)

In [38]:
df.describe()

           summarize       negative
count  111699.000000  111699.000000
mean        0.219895       0.101317
std         0.749348       0.301749
min         0.000000       0.000000
25%         0.000000       0.000000
50%         0.000000       0.000000
75%         0.000000       0.000000
max         6.000000       1.000000

In [39]:
df = df.drop(axis='columns', labels=['summarize'])

In [40]:
df.to_csv("./../data/processed/train.csv")

In [43]:
df = pd.read_csv("./../data/raw/test.csv")



# df['summarize'] = (df['toxic'] + df['severe_toxic'] + df['obscene'] + df['threat'] + df['insult'] + df['identity_hate'])
# df = df.drop(axis='columns', labels=['id', 'toxic', 'severe_toxic', 'obscene', 'threat', 'insult', 'identity_hate'])
# df = df.copy()
# df['negative'] = (df['summarize'] > 0).astype(int)
df.to_csv("./../data/processed/test.csv")